# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ae3597d382f67c29bea41a677bfb058e00d78a37380212c021c685cbeb6082abcd8613226631b72aed891a137c4897d3c441fdb82d9ec17403baf8432e485d2

test:
  secret_key_base: 9463696c703ac07b1c3b79400db7f9c8948d7fa37631ca7f825785b5aeb268810420e6db97a84bead5d68795ababecf9bfb92d7cabff8215f9b1003391b26962

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
